franklin-ai/darwin-v7

Cargo.toml, README.md, src/main.rs
A skeleton package to grab the darwin-v7 name in crates.io
=> Register crate in crates.io

.vscode/launch.json, Cargo.toml, src/classes.rs, src/client.rs, src/config.rs, src/datasets.rs, src/item.rs, src/lib.rs, src/team.rs, src/utils.rs, src/workflow.rs
I've added a few more endpoints for usage and have resolved the issue with data not loading.  As described before this was due to the requirement that the external storage have different names in the different accounts.
Implemented traits for endpoints to allow for easier testing / implementation by different clients if ever required.
Unit test coverage is low, and will be improved in subsequent PRs prior to release.
=> New API Additions

src/classes.rs, src/client.rs, src/config.rs, src/datasets.rs, src/filter.rs, src/item.rs, src/team.rs, src/workflow.rs
Fixes a bunch of clippy errors
=> fix: cargo fmt and clippy fixes

Cargo.toml
=> release: version 0.1.2

.github/workflows/CI.yml, src/classes.rs, src/datasets.rs, src/filter.rs, src/team.rs, src/workflow.rs
Adding back Faker to fix build
=> fix: add back Faker

Cargo.toml, src/annotation.rs, src/datasets.rs, src/export.rs, src/lib.rs, src/team.rs
This PR aims to add structs to be able to parse a V7 Dataset Export JSON result.
To be able to make calculations of area segmentations and attributes labelled a bit more easier
=> feat: add export structs

src/datasets.rs
Make the filter payload optional for generating data exports.
Add some extra fields to the Export response.
=> feat: Make the filter for exports optional

Cargo.toml, src/datasets.rs, src/item.rs
Adds the functionality to get the item reports and render the returned csv as an ItemReport datastructure
=> feat: Generate item reports from csv

src/datasets.rs, src/item.rs, src/workflow.rs
Upon testing creation of datasets using V2.0, the following fixes are required that define the responses and payloads to the API endpoints
=> fix: v2 structs

src/workflow.rs
This PR adds an API endpoint to update an existing workflow
=> feat: update workflow api

Cargo.toml
Version 0.2.0
Version 2.0 data structures and endpoints
e973b31 (HEAD -> release/0.1.5, origin/release/0.1.5) chore: bump version
971ee59 (origin/feat/update-workflow-v2, feat/update-workflow-v2) feat: update workflow api
60452fc (origin/fix/workflow-structs, fix/workflow-structs) fix: v7 v2 structs
9509b3c (origin/feat/get-workflows, feat/get-workflows) fix: clippy
7685c15 feat: set stage of a dataset workflow
77b264a fix: make endpoint in workflows.rs
3541ac1 feat: filter workflow for dataset
1a1156c feat: add method to get workflows
d995ec8 (origin/feat/create-v2-workflow, feat/create-v2-workflow) fix: cargo fmt
6c29591 fix: struct types
3d1fa75 fix: deriving traits
5c46c37 fix: update list of assignees
72d693d fix: add new stage type
8664072 fix: make vars public
a3b3e78 feat: add v2 …
=> Release: 0.2.0

src/export.rs
Adds structs to parse an export from V7labs in Darwin JSON 2.0
=> feat: add structs to support V2.0 Darwin JSON

src/export.rs
Makes the structs available in library references
=> fix: make darwin json 2.0 structs public

Cargo.toml, src/datasets.rs, src/utils.rs, src/workflow.rs
Updates dataset methods for the following:
1. Generate export method using version 2.0
2. Adds a method to update a dataset that adds annotation hotkeys
=> feat: update dataset methods

.github/workflows/renovate.yml
No
No
Adds Slack notification to the `#fra-ros-action-failures` channel when the renovate workflow fails.
Visibility of schedule workflow failures
This section is optional, however if you have any concerns or questions regarding aspects of the PR, they can be included here. Including the concerns in this section ensures that they …
=> RS-866: Add slack notification on failure

src/annotation.rs, src/team.rs
In our ongoing efforts to improve the resilience and reliability of the `darwin-v7` codebase, we're addressing the need to better handle optional values from the V7 API. Experience has shown that the API's responses can be inconsistent with its documentation, leading to potential failures in our system when expected properties are missing or incorrectly typed.
This PR is part of a series aimed at wrapping every possible value from API responses in `Option<>`, thereby shifting the responsibility of checking for values downstream to the consumer. This approach ensures that API calls do not fail due to missing or incorrect properties, improving overall system stability.
- **File Updated**: `team.rs`
- **Traits Affected**:
- `TeamDescribeMethods`
- `TeamDataMethods`
- All basic value types …
=> chore: Team Response Options #FRADATA-609

Cargo.lock
Fix deny check by updating backtrace
=> fix: update backtrace

deny.toml
- Updates deny.toml
This section is also optional and should include anything else that you would like to discuss in the PR review that is not captured elsewhere.
=> RS-2681: Update deny.toml in all repos

.github/workflows/CI.yml, .github/workflows/release.yml
Creates workflow to publish a release
So we release darwin-v7 versions!
=> task: add publish crate action

CHANGELOG.md, Cargo.lock, Cargo.toml, RELEASE.md
Updates version in Cargo.toml and adds release doc
So we can release and publish
=> chore: release 0.4.0

.github/workflows/renovate.yml, renovate-self-hosted.js, renovate.json
N/A
N/A
- Fixes the renovate workflow
It repeatedly fails and causes noise in a Slack alerts channel …
=> RS-2426: Update renovate job

Cargo.toml
https://franklin-ai.atlassian.net/browse/RS-3467
This section is also optional and should include …
=> RS-3467: Add repository to Cargo.toml

Cargo.lock, Cargo.toml, src/annotation.rs, src/bin/main.rs, src/client.rs
This section is also optional and should include anything else that you would like to discuss in the PR …
=> RS-3603: Remove hello world bin

.github/workflows/CI.yml, src/item.rs
https://franklin-ai.atlassian.net/browse/RS-3604
- Fix lints that are now enabled by default
CI is failing
This section is also optional and should include anything else that you would like to discuss in the PR review that is not captured elsewhere.
=> RS-3604: Fix Rust 1.81 lint by removing tarpaulin

CHANGELOG.md, Cargo.lock, Cargo.toml
This PR cuts a new release of `darwin-v7`.
We would like to ship a release with the latest dependencies available.
=> release: v0.6.0

.github/workflows/CI.yml, Cargo.lock, deny.toml
This PR updates the CI configuration to run in more situations:
* All PRs
* Merge queue
* Manual trigger.
Reduce the change of breaking the build on main.
=> task: Run CI checks in more situations

Cargo.lock, src/workflow.rs
Fixes structs to allow optional field values when interacting with V7 `Workflow`
=> fix: optional workflow fields

src/item.rs
Update structs returned when querying for `list_dataset_items` 
So we can successfully pull down dataset items
=> fix: update structs returned when querying `list_dataset_items`

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: 0.7.1

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: 0.7.3

Cargo.lock, src/client.rs, src/datasets.rs, src/imports.rs, src/item.rs
Fixes Clippy errors and rust security checks
=> fix: CI checks

src/datasets.rs
Dataset method to update instructions
=> feat: add method to update instructions

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: release 0.8.0

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: release 0.8.1
