franklin-ai/darwin-v7

Cargo.toml
src/client.rs
src/config.rs
src/lib.rs
src/main.rs
src/team.rs

This PR adds a basic V7 client with tests.  There is a raw client that is used to provide the basic headers required by the V7 api.
The intent is that `V7Client` will serve to interact with both the 1.0 and 2.0 versions of the V7 api and that the methods that the client is passed to will then manage the differences between the two version.  
Say we wanted to list the datasets for a team in V7, we'd use the client as follows:
```rust
use darwin_v7::clients::V7Client;
use darwin_v7::config::Config;
use darwin_v7::datasets::{Dataset, DatasetItem};
use std::io::Read;
#[tokio::main]
async fn main() {
let config = Config::from_file("/some/config.yaml").unwrap();
let client = V7Client::from_config(&config, Some(&"some-team".to_string())).unwrap();
let datasets = …
```

feat: Add a basic client

---

.github/workflows/renovate.yml
Cargo.toml

1. Add renovate
2. Bump version to 0.1.1 for release into crates.io and downstream consumption.

feat:Renovate + bump version

---

src/annotation.rs
src/export.rs

This PR adds a type complex_polygon - even though conceptually it is a list of polygons, exports from V7 include the annotation type as "complex_polygon" differing from "polygon". Adding a separate type helps clarify the structure of the polygon parsed.

feat: add complex_polygon as an annotation_type

---

src/datasets.rs

Comment out the ExportMetadata as it is not being returned from V7

fix: Remove metadata from Export results

---

src/annotation.rs
src/export.rs

This PR fixes the type definition of ComplexPolygons, and adds an explicit test to make sure we're getting what we expect in the unit test that tests for parsing.
Previously the complex polygon was decoding to a `Tag`, but we didn't actually check this in the test.

fix: Fix ComplexPolygon parsing

---

src/comment.rs

There's a typo in the POST route we use to add a comment to an item.
Source: https://docs.v7labs.com/reference/comments-thread-create

fix: comment_tread to comment_threads route typo

---

src/datasets.rs

This PR fixes the response status code to check for 201 rather than 200 to set the workflow to a dataset successfully

fix: response status code on setting a workflow is 201

---

src/classes.rs
src/comment.rs
src/workflow.rs

Changes the value types for `BoundingBox` to `f32`, as the Darwin API was returning floats in responses.
Also removes `Eq` traits from anything that consumes a `BoundingBox`, as floats don't implement `Eq`.
So we can make API calls that work, because we get deserialisation errors on response otherwise.

fix: Comment thread response type

---

src/datasets.rs

Adds a method on `DatasetDataMethods` for `update_batch_size` to change the task batch size in a dataset (read: the number of items a labeller can self-assign at a single time).
So we can limit the number of items labellers are self-assigning from their datasets.

feat: Add dataset update route to change batch size

---

src/datasets.rs

Allows a filter to be set when setting a stage
So we can update stage only for a few items if and when required

fix: let caller decide set_stage filter

---

src/annotation.rs
src/export.rs
src/utils.rs
src/workflow.rs

Updates Darwin JSON v2.0 struct for annotations and explicitly defines the annotation type as a bounding box or polygon or tag

Fix: v2 annotation types

---

src/export.rs

Adds the default trait to the export struct 
Lots of optional fields - not necessary to populate/use all each time the struct is referenced

fix: add default for export structs

---

src/datasets.rs
src/imports.rs
src/lib.rs

In this repo, we strive to follow the [conventional comments](https://conventionalcomments.org/) guidebook for providing feedback on PRs. Please adhere to this guidebook for a more efficient review process.
This PR addresses part of [FRADATA-543](https://franklin-ai.atlassian.net/browse/FRADATA-543) - Migrate annotation imports to `darwin-v7`.
There are no dependencies on other PRs for this update.
Implemented the `import_annotation` method in the `darwin-v7` crate. This method encapsulates the functionality for importing annotations into datasets, previously done through manual V7 endpoint calls.
The integration of the `import_annotation` method into the `darwin-v7` crate centralizes dataset management functionalities, enhancing code maintainability and consistency. This update is a step …

feat:  migrate annotation import #FRADATA-543

---

src/annotation.rs

Updates the Keypoint structure to implement PartialEq and PartialOrd so as to be able to compare linestrings( list of keypoints) against each other

fix: derive eq method to compare list of keypoints

---

src/annotation.rs

-------
Color should be an option as it is not always present, and add support for a new field called raster_layer.
V7 annotation class has a new field, and the `_color` field is not always present, so we made it optional.
This section is also optional and should include anything else that you would like to discuss in the PR review that is not …

Color should be an Option as it is not always present and add support for a new field called raster_layer

---

src/annotation.rs
src/datasets.rs
src/item.rs
src/workflow.rs

📚 **Please review according to the [conventional comments](https://conventionalcomments.org/) guidebook. Your feedback is vital for maintaining our code quality and team understanding.**
---
---
---
🔨 **Changes Made:**
- Updated return types of `workflow` client functions in darwin-v7 to use `Option<>` for all API response properties.
- Modified functions in `WorkflowMethods` trait and `Workflow` struct to handle optional values accordingly.
- Implemented double-option pattern (`Vec<Option<T>>`) for lists that could contain `null` values.
---
🎯 **Purpose & Context:**
- Our experience with the V7 API has shown that response types are not always consistent with documentation, leading to potential runtime errors.
- By wrapping API response properties in `Option<>`, we pass the responsibility …

chore: Wrap API Response Properties in `Option<>` for `workflow` Client Calls in darwin-v7 #FRADATA-609

---

src/annotation.rs

📚 **Please review this PR according to the [conventional comments](https://conventionalcomments.org/) guide.**
---
---
---
🔨 **Annotation Response Refactor:**
- Refactored annotation response handling in `darwin-v7` to encapsulate all properties within `Option<>`.
- Adjusted methods in `AnnotationsClass` struct to use optional values.
- Introduced a pattern of `Vec<Option<T>>` for annotation lists, accommodating potential `null` values in the responses.
---
🎯 **Rationale & Context:**
- Inconsistencies in annotation responses from the V7 API have been observed, sometimes diverging from the documented types.
- Utilizing `Option<>` for annotation properties ensures more robust error handling and system resilience by explicitly managing the presence or absence of data.
- This refactor is a …

chore: Refactor annotations response as options #FRADATA-609

---

Cargo.lock

`cargo update`
This section is also optional and should include anything else that you would like to …

RS-2425: Bump deps in lock file to avoid multiple CVEs

---

Cargo.lock
Cargo.toml
src/annotation.rs
src/comment.rs
src/datasets.rs
src/export.rs
src/item.rs
src/team.rs
src/workflow.rs

Updates Darwin API response structures to be optional values
So that we can handle the unanticipated API changes

chore: update responses to be optional 

---

src/client.rs
src/datasets.rs
src/export.rs
src/item.rs
src/workflow.rs

Removes deprecated, unsupported darwin v1 api calls and api request and response structures
You Aren't Going to Need It

chore: remove v1 structs

---

.github/workflows/CI.yml
Cargo.lock
deny.toml

RUSTSEC-2024-0019 is in the lock file.
n/a
Update the lock file
- Add CI to run https://github.com/EmbarkStudios/cargo-deny
Catch CVEs earlier.
This section is also optional and should include anything else that you would like to discuss in the PR review that is not captured elsewhere.

chore(deps): Add cargo-deny and avoid CVEs in lock

---

Cargo.lock

```
error[vulnerability]: Degradation of service in h2 servers with CONTINUATION Flood
Error:    ┌─ /home/runner/work/darwin-v7/darwin-v7/Cargo.lock:52:1
│
52 │ h2 0.4.3 registry+https://github.com/rust-lang/crates.io-index
│ -------------------------------------------------------------- security vulnerability detected
```
Updates h2 lock version

fix: update h2 version

---

.github/workflows/CI.yml
.github/workflows/release.yml

https://franklin-ai.atlassian.net/issues/RS-2215
- Use a maintained Github Action
- The current one is deprecated

RS-2215: Replace deprecated actions-rs/toolchain

---

Cargo.lock
Cargo.toml
src/annotation.rs
src/client.rs

https://franklin-ai.atlassian.net/browse/RS-3602
- Add features "native-tls" and "rustls-tls" to allow choosing the HTTPS stack - default is "native-tls" (openssl) which is not changed
rosalind is trying to avoid the openssl stack
This section is also optional and should include anything else that you would like to discuss in the PR review that …

RS-3602: Allow selecting https stack

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

N/A
N/A
Bump crate version
In preparation for release
N/A

chore: Bump version

---

Cargo.lock
Cargo.toml

This PR upgrades `fake` to version `3.0.0`.
We have upstream repos that would like to upgrade, and this requires `darwin-v7` to be on the same version.

task: Upgrade fake to 3.0.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR prepares a release of version `0.7.0` according to `RELEASE.md`.
So we can have a release with up to date dependencies.

chore: Release 0.7.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR prepares the release of version `0.7.2` according to `RELEASE.md`.
We want a release that includes that latest major bump of the `fake` crate.

task: Prepare release `v0.7.2`

---

src/annotation.rs
src/workflow.rs

Updates the response struct returned from V7 API calls.
So we receive the correct response struct.

fix: update V7 API response structs

---

Cargo.lock

https://franklin-ai.atlassian.net/issues/RS-4830
`cargo update` to remove problematic versions of `ring` and `rustls` from the lock file
This section is also optional and should …

RS-4830: Update deps to avoid RUSTSEC-2025-0007
